import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import {clientRoutes} from '../src/client-routes.js';
const clientId='11dcb25b-f1d8-4722-ad06-a0449d82362e',userId='21dcb25b-f1d8-4722-ad06-a0449d82362e';
async function run({owner=true,existing=false,staff=false,email='client@example.com',fail=''}={}){const keys=['CLIENT_MANAGEMENT_ENABLED','LEAD_WORKFLOW_ENABLED','SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY'],saved=Object.fromEntries(keys.map(k=>[k,process.env[k]]));Object.assign(process.env,{CLIENT_MANAGEMENT_ENABLED:'true',LEAD_WORKFLOW_ENABLED:'true',SUPABASE_URL:'https://test.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'test-key'});const original=global.fetch,calls=[],auth=[];global.fetch=async(url,opts)=>{auth.push({url:String(url),opts});return {ok:true,json:async()=>({id:userId})}};const c={query:async(sql,params)=>{calls.push({sql,params});if(fail&&sql.includes(fail))throw Error('Test database error');if(sql.includes('from public.crm_clients'))return {rowCount:1,rows:[{id:clientId,email:'client@example.com'}]};if(sql.includes('from auth.users'))return {rowCount:existing?1:0,rows:existing?[{id:userId}]:[]};if(sql.includes('from public.crm_staff'))return {rowCount:staff?1:0,rows:[]};return {rowCount:1,rows:[]}},release:()=>{}};const app=express();app.use(express.json());app.use(clientRoutes({pool:{query:c.query,connect:async()=>c},requireOwner:(req,res,next)=>owner?(req.owner={id:'owner'},next()):res.status(403).json({error:'Owner only'})}));app.use((err,req,res,next)=>res.status(500).json({error:'Setup failed'}));const server=app.listen(0,'127.0.0.1');try{await new Promise(r=>server.once('listening',r));const r=await original('http://127.0.0.1:'+server.address().port+'/portal-account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId,email})});return {status:r.status,data:await r.json(),calls,auth}}finally{await new Promise(r=>server.close(r));global.fetch=original;for(const k of keys)if(saved[k]===undefined)delete process.env[k];else process.env[k]=saved[k]}}
test('only Owner creates or links client credentials',async()=>{const r=await run({owner:false});assert.equal(r.status,403);assert.equal(r.calls.length,0);assert.equal(r.auth.length,0)});
test('client email mismatch blocks provisioning',async()=>{const r=await run({email:'other@example.com'});assert.equal(r.status,400);assert.equal(r.auth.length,0)});
test('new login securely creates account and forces first password change',async()=>{const r=await run();assert.equal(r.status,201);assert.ok(r.data.temporaryPassword.length>=32);assert.equal(r.data.mustChangePassword,true);assert.ok(r.calls.some(c=>c.sql.includes('insert into public.crm_client_login_accounts')));assert.equal(r.calls.at(-1).sql,'COMMIT');const sent=JSON.parse(r.auth[0].opts.body);assert.equal(sent.email_confirm,true);assert.equal(sent.password,r.data.temporaryPassword)});
test('existing client login links without changing password',async()=>{const r=await run({existing:true});assert.equal(r.status,200);assert.equal(r.auth.length,0);assert.equal(r.data.temporaryPassword,null)});
test('staff identity cannot be assigned as customer login',async()=>{const r=await run({existing:true,staff:true});assert.equal(r.status,400);assert.ok(!r.calls.some(c=>c.sql.includes('insert into public.crm_client_portal_access')))});
test('definite provisioning failure cleans new Auth account',async()=>{const r=await run({fail:'insert into public.crm_client_portal_access'});assert.equal(r.status,500);assert.equal(r.auth.at(-1).opts.method,'DELETE')});
test('ambiguous commit retains Auth and requires reconciliation',async()=>{const r=await run({fail:'COMMIT'});assert.equal(r.status,503);assert.ok(!r.auth.some(c=>c.opts.method==='DELETE'));assert.equal(r.data.temporaryPassword,undefined)});
