import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';
import {employeeActivityRoutes} from '../src/employee-activity-routes.js';import {workMutation} from '../src/work-activity.js';
const actor='11111111-1111-4111-8111-111111111111',lead='22222222-2222-4222-8222-222222222222',requestId='33333333-3333-4333-8333-333333333333';
const body={leadId:lead,requestId,kind:'call',outcome:'connected',durationSeconds:60,note:'Client requested pricing',nextFollowUp:null};
async function run({owner=false,permissions=['leads:read'],method='POST',path='/calls',payload=body,query=()=>({rowCount:0,rows:[]})}={}){
 const calls=[],db={query:async(sql,params)=>{calls.push({sql,params});return query(sql,params)},release:()=>{}};const app=express();app.use(express.json());app.use(employeeActivityRoutes({pool:{...db,connect:async()=>db},authorize:(req,res,next)=>{req.actor={id:actor,owner,permissions,role:owner?'owner':'sales'};next()}}));app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{const response=await fetch('http://127.0.0.1:'+server.address().port+path,{method,headers:{'Content-Type':'application/json'},...(method==='POST'?{body:JSON.stringify(payload)}:{})});return{status:response.status,data:await response.json(),calls}}finally{await new Promise(r=>server.close(r))}
}
test('performance report is Owner-only',async()=>{const r=await run({method:'GET',path:'/report?from=2026-10-01&to=2026-10-11'});assert.equal(r.status,403);assert.equal(r.calls.length,0)});
test('staff without lead access cannot log calls',async()=>{const r=await run({permissions:[]});assert.equal(r.status,403);assert.equal(r.calls.length,0)});
test('call actor cannot be forged from body',async()=>{const r=await run({payload:{...body,actorId:actor}});assert.equal(r.status,400);assert.equal(r.calls.length,0)});
test('bad duration and impossible dates fail before DB',async()=>{for(const payload of [{...body,durationSeconds:-1},{...body,nextFollowUp:'2026-02-30'}]){const r=await run({payload});assert.equal(r.status,400);assert.equal(r.calls.length,0)}});
test('missing lead rolls back without call',async()=>{const r=await run();assert.equal(r.status,404);assert.deepEqual(r.calls.map(c=>c.sql),['BEGIN','select id from public.crm_leads where id=$1','ROLLBACK'])});
test('call insert uses session actor and retry key',async()=>{const r=await run({query:sql=>sql.startsWith('select id')?{rowCount:1,rows:[{id:lead}]}:sql.startsWith('insert into')?{rowCount:1,rows:[{id:4}]}:{rowCount:0,rows:[]}});assert.equal(r.status,201);const saved=r.calls.find(c=>c.sql.startsWith('insert'));assert.equal(saved.params[0],actor);assert.equal(saved.params[2],requestId);assert.match(saved.sql,/on conflict\(actor_id,request_id\) do nothing/);assert.equal(r.calls.at(-1).sql,'COMMIT')});
test('identical retry returns original call',async()=>{const r=await run({query:sql=>sql.startsWith('select id')?{rowCount:1,rows:[{id:lead}]}:sql.startsWith('select *,')?{rowCount:1,rows:[{id:4,lead_id:lead,kind:body.kind,outcome:body.outcome,duration_seconds:60,note:body.note,next_follow_up:null}]}:{rowCount:0,rows:[]}});assert.equal(r.status,200);assert.equal(r.data.created,false);assert.equal(r.data.activity.id,4)});
test('retry key with changed content rejects',async()=>{const r=await run({query:sql=>sql.startsWith('select id')?{rowCount:1,rows:[{id:lead}]}:sql.startsWith('select *,')?{rowCount:1,rows:[{lead_id:lead,kind:'call',outcome:'busy',duration_seconds:60,note:body.note}]}:{rowCount:0,rows:[]}});assert.equal(r.status,409);assert.equal(r.calls.at(-1).sql,'ROLLBACK')});
test('call history scopes to own actor',async()=>{const r=await run({method:'GET'});assert.equal(r.status,200);assert.match(r.calls[0].sql,/a.actor_id=\$1/);assert.deepEqual(r.calls[0].params,[actor])});
test('Owner range rejects reversed impossible and excessive dates',async()=>{for(const path of ['/report?from=2026-10-11&to=2026-10-01','/report?from=2026-02-30&to=2026-03-01','/report?from=2020-01-01&to=2026-10-11']){const r=await run({owner:true,method:'GET',path});assert.equal(r.status,400);assert.equal(r.calls.length,0)}});
test('Owner summary and detail use India day filters',async()=>{const r=await run({owner:true,method:'GET',path:'/report?from=2026-10-01&to=2026-10-11&employeeId='+actor});assert.equal(r.status,200);assert.equal(r.calls.length,2);assert.equal(r.calls[0].params[0],'2026-10-01T00:00:00+05:30');assert.equal(r.calls[0].params[3],actor);assert.equal(r.calls[1].params[2],actor);assert.match(r.calls[1].sql,/e.actor_id=\$3/)});
test('task completion and log commit together',async()=>{const calls=[],client={query:async(sql,p)=>{calls.push({sql,p});if(sql.startsWith('select'))return{rows:[{id:1,status:'in_progress'}]};if(sql.startsWith('update'))return{rowCount:1,rows:[{id:1,status:'done'}]};return{rows:[]}},release:()=>{}};await workMutation({connect:async()=>client},{id:actor,role:'developer'},'tasks','update task returning *',[1],'updated');const event=calls.find(c=>c.sql.startsWith('insert into public.crm_staff_work_activity'));assert.equal(event.p[1],'completed');assert.equal(calls.at(-1).sql,'COMMIT')});
test('re-saving done task does not inflate completion',async()=>{const calls=[],client={query:async sql=>{calls.push(sql);return{rowCount:1,rows:[{id:1,status:'done'}]}},release:()=>{}};await workMutation({connect:async()=>client},{id:actor,role:'developer'},'tasks','update task returning *',[1],'updated');assert.equal(calls.some(s=>s.startsWith('insert')),false)});
test('failed log rolls back task mutation',async()=>{const calls=[],client={query:async sql=>{calls.push(sql);if(sql.startsWith('insert'))throw Error('audit failed');return{rowCount:1,rows:[{id:1,status:sql.startsWith('select')?'todo':'done'}]}},release:()=>{}};await assert.rejects(workMutation({connect:async()=>client},{id:actor,role:'developer'},'tasks','update task returning *',[1],'updated'),/audit failed/);assert.equal(calls.at(-1),'ROLLBACK');assert.equal(calls.includes('COMMIT'),false)});
