import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';
import {paymentControlRoutes} from '../src/payment-control-routes.js';import {advanceRequired} from '../src/advance-policy.js';
async function run({role='owner',grant=true,used=false,path='/quotations/1',body={mode:'amount',value:50,reason:'Agreed advance'},fail=''}={}){const calls=[];const c={query:async(sql,params)=>{calls.push({sql,params});if(fail&&sql.includes(fail))throw Error('Simulated failure');if(sql.includes('crm_payment_review_grants'))return {rowCount:grant?1:0,rows:[]};if(sql.startsWith('select id,amount'))return {rowCount:1,rows:[{id:1,amount:100,status:'sent',advance_percent:30,advance_amount:null}]};if(sql.startsWith('select 1 from public.crm_invoices'))return {rowCount:used?1:0,rows:[]};if(sql.includes('crm_business_policy'))return {rowCount:1,rows:[{advance_percent:30}]};return {rowCount:1,rows:[]}},release:()=>{}};const app=express();app.use(express.json());app.use(paymentControlRoutes({pool:{connect:async()=>c,query:c.query},authorize:(req,res,next)=>{req.actor={id:'actor',role,owner:role==='owner',permissions:['quotations:read']};next()}}));app.use((err,req,res,next)=>res.status(500).json({error:err.message}));const server=app.listen(0,'127.0.0.1');try{await new Promise(r=>server.once('listening',r));const r=await fetch('http://127.0.0.1:'+server.address().port+path,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,data:await r.json(),calls}}finally{await new Promise(r=>server.close(r))}}
test('advance math uses saved percentage/fixed amount, paid cents and remaining cap',()=>{assert.equal(advanceRequired(33000,0,30),9900);assert.equal(advanceRequired(33000,5000,30),4900);assert.equal(advanceRequired(33000,12000,30),0);assert.equal(advanceRequired(100,20,30,50),30);assert.equal(advanceRequired(100,0,0),0);assert.equal(advanceRequired(1.01,0,30),.3)});
test('Sales HR Accountant Manager Developer cannot set advance',async()=>{for(const role of ['sales','hr','accountant','manager','developer']){const r=await run({role});assert.equal(r.status,403);assert.ok(!r.calls.some(c=>c.sql.startsWith('update')))}});
test('Super Admin needs Owner authorization and revocation lock',async()=>{const r=await run({role:'super_admin',grant:false});assert.equal(r.status,403);assert.match(r.calls.find(c=>c.sql.includes('crm_payment_review_grants')).sql,/for share/)});
test('Owner and delegated Super Admin can set fixed advance and audited actor',async()=>{for(const role of ['owner','super_admin']){const r=await run({role});assert.equal(r.status,200);assert.deepEqual(r.calls.find(c=>c.sql.startsWith('update public.crm_quotations')).params,[1,30,50]);assert.equal(r.calls.find(c=>c.sql.startsWith('insert into public.crm_payment_control_audit')).params[2],role);assert.equal(r.calls.at(-1).sql,'COMMIT')}});
test('percentage mode clears prior fixed override',async()=>{const r=await run({body:{mode:'percent',value:40,reason:'New agreement'}});assert.equal(r.status,200);assert.deepEqual(r.calls.find(c=>c.sql.startsWith('update public.crm_quotations')).params,[1,40,null])});
test('advance cannot change after payment submission or approval',async()=>{const r=await run({used:true});assert.equal(r.status,409);assert.ok(!r.calls.some(c=>c.sql.startsWith('update')))});
test('advance cannot exceed quote total',async()=>{const r=await run({body:{mode:'amount',value:101,reason:'New agreement'}});assert.equal(r.status,400);assert.ok(!r.calls.some(c=>c.sql.startsWith('update')))});
test('missing reason and amount precision rejected before DB',async()=>{for(const body of [{mode:'percent',value:30,reason:''},{mode:'amount',value:.001,reason:'Terms'},{mode:'percent',value:101,reason:'Terms'}]){const r=await run({body});assert.equal(r.status,400);assert.equal(r.calls.length,0)}});
test('audit failure rolls back terms update',async()=>{const r=await run({fail:'insert into public.crm_payment_control_audit'});assert.equal(r.status,500);assert.equal(r.calls.at(-1).sql,'ROLLBACK')});
test('default percentage is separate from UPI destination and fully audited',async()=>{const r=await run({role:'super_admin',path:'/default',body:{advancePercent:40,reason:'Company advance rule'}});assert.equal(r.status,200);assert.deepEqual(r.calls.find(c=>c.sql.startsWith('update public.crm_business_policy')).params,[40,'actor']);assert.ok(!r.calls.some(c=>/set upi/.test(c.sql)))});
