import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {paymentRoutes,paymentAmount} from '../src/payment-routes.js';
async function run({role='owner',grant=true,credited=false,enabled=true,state='pending',action='approved',fail='',due='100',body}={}){
 const old=process.env.PAYMENT_REVIEW_ENABLED;process.env.PAYMENT_REVIEW_ENABLED=String(enabled);
 const calls=[],releases=[],client={query:async(sql,params)=>{calls.push({sql,params});if(fail&&sql.includes(fail))throw Error('DB failure');if(sql.includes('crm_payment_review_grants'))return {rowCount:grant?1:0,rows:[]};if(sql.startsWith('select submission_id'))return {rowCount:credited?1:0,rows:credited?[{submission_id:99}]:[]};if(sql.startsWith('select *'))return {rowCount:1,rows:[{id:1,invoice_id:2,amount:'30',reference:'UPI-123',status:state}]};if(sql.startsWith('select id,amount'))return {rowCount:1,rows:[{id:2,amount:due,paid_amount:'0',status:'issued'}]};return {rowCount:1,rows:[]}},release:b=>releases.push(b)};
 const app=express();app.use(express.json());app.use('/payments',paymentRoutes({pool:{connect:async()=>client,query:client.query},authorize:(req,res,next)=>{req.actor={id:'owner-id',role,owner:role==='owner',permissions:['payments:read']};next()},requireOwner:(req,res,next)=>req.actor.owner?next():res.sendStatus(403)}));app.use((err,req,res,next)=>res.status(500).json({error:err.message}));const server=app.listen(0,'127.0.0.1');try{await new Promise(r=>server.once('listening',r));const response=await fetch('http://127.0.0.1:'+server.address().port+'/payments/1/decision',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body??{action,reason:'Bank receipt verified'})});return {status:response.status,data:await response.json(),calls,releases}}finally{await new Promise(r=>server.close(r));if(old===undefined)delete process.env.PAYMENT_REVIEW_ENABLED;else process.env.PAYMENT_REVIEW_ENABLED=old}
}
test('disabled payment review never accesses DB',async()=>{const r=await run({enabled:false});assert.equal(r.status,503);assert.equal(r.calls.length,0)});
test('Sales HR Accountant cannot approve',async()=>{for(const role of ['sales','hr','accountant']){const r=await run({role});assert.equal(r.status,403);assert.equal(r.calls.length,0)}});
test('Super Admin must have Owner delegation',async()=>{const r=await run({role:'super_admin',grant:false});assert.equal(r.status,403);assert.match(r.calls[1].sql,/for share/);assert.equal(r.calls.some(c=>c.sql.startsWith('insert')),false)});
test('approval locks invoice and submission, commits ledger and audit atomically',async()=>{const r=await run();assert.equal(r.status,200);assert.equal(r.data.status,'approved');assert.equal(r.calls.filter(c=>c.sql.includes('for update')).length,2);assert.equal(r.calls.filter(c=>c.sql.startsWith('insert')).length,2);assert.equal(r.calls.at(-1).sql,'COMMIT');assert.deepEqual(r.releases,[false]);assert.deepEqual(r.calls.find(c=>c.sql.startsWith('update public.crm_invoices')).params,[2,30,'part_paid'])});
test('repeat approval cannot double credit',async()=>{const r=await run({state:'approved'});assert.equal(r.status,200);assert.equal(r.data.unchanged,true);assert.equal(r.calls.some(c=>/^(insert|update)/.test(c.sql)),false)});
test('rejected payment can reopen or approve after review',async()=>{for(const action of ['reopened','approved']){const r=await run({state:'rejected',action});assert.equal(r.status,200);assert.equal(r.data.status,action==='reopened'?'pending':'approved');assert.equal(r.calls.find(c=>c.sql.startsWith('insert into public.crm_payment_audit')).params[3],action)}});
test('approved payment cannot reject',async()=>{const r=await run({state:'approved',action:'rejected'});assert.equal(r.status,409);assert.equal(r.calls.at(-1).sql,'ROLLBACK')});
test('overpayment fails without writes',async()=>{const r=await run({due:'20'});assert.equal(r.status,409);assert.equal(r.calls.some(c=>c.sql.startsWith('insert')),false)});
test('audit insertion failure rolls back ledger and balance',async()=>{const r=await run({fail:'insert into public.crm_payment_audit'});assert.equal(r.status,500);assert.equal(r.calls.at(-1).sql,'ROLLBACK');assert.equal(r.calls.some(c=>c.sql==='COMMIT'),false)});
test('uncertain COMMIT requires reconciliation without rollback or success',async()=>{const r=await run({fail:'COMMIT'});assert.equal(r.status,503);assert.match(r.data.error,/uncertain/);assert.equal(r.calls.some(c=>c.sql==='ROLLBACK'),false);assert.deepEqual(r.releases,[true])});
test('review requires reason before DB',async()=>{const r=await run({body:{action:'approved',reason:''}});assert.equal(r.status,400);assert.equal(r.calls.length,0)});
test('amount rejects sub-paisa precision',()=>{assert.equal(paymentAmount.safeParse(0.001).success,false);assert.equal(paymentAmount.safeParse(1.23).success,true)});

test('same bank reference cannot be credited against a different invoice',async()=>{const r=await run({credited:true});assert.equal(r.status,409);assert.ok(!r.calls.some(c=>c.sql.startsWith('insert')));assert.ok(r.calls.some(c=>c.sql.includes('pg_advisory_xact_lock')))});
