import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';
import {quotationRoutes,quotationTokenHash} from '../src/quotation-routes.js';
const body={clientName:'Customer',clientEmail:'customer@example.com',clientPhone:'+919999999999',title:'Services',status:'sent',items:[{name:'Website',quantity:2,unitPrice:15000},{name:'Maintenance',quantity:3,unitPrice:1000}]};
async function run({role='sales',path='/',payload=body,quoteStatus='sent',creator='actor',fail='',floor=0}={}){
 const calls=[],client={query:async(sql,params)=>{calls.push({sql,params});if(fail&&sql.includes(fail))throw Error('failure');if(sql.includes('crm_business_policy'))return {rowCount:1,rows:[{quotation_floors:{INR:floor},advance_percent:30}]};if(sql.startsWith('select id from public.crm_clients'))return {rowCount:0,rows:[]};if(sql.startsWith('insert into public.crm_clients'))return {rowCount:1,rows:[{id:'customer-id'}]};if(sql.startsWith('insert into public.crm_quotations'))return {rowCount:1,rows:[{id:1,amount:params[2],status:params[4],requires_approval:params[6]}]};if(sql.startsWith('select status'))return {rowCount:1,rows:[{status:quoteStatus,requires_approval:false,created_by:creator}]};return {rowCount:1,rows:[]}},release:()=>{}};
 const app=express();app.use(express.json());app.use(quotationRoutes({pool:{query:client.query,connect:async()=>client},authorize:(req,res,next)=>{req.actor={id:'actor',role,owner:role==='owner',permissions:role==='sales'?['quotations:read','quotations:create']:[]};next()}}));app.use((e,req,res,next)=>res.status(500).json({error:e.message}));const server=app.listen(0,'127.0.0.1');try{await new Promise(r=>server.once('listening',r));const response=await fetch('http://127.0.0.1:'+server.address().port+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});return {status:response.status,data:await response.json(),calls}}finally{await new Promise(r=>server.close(r))}
}
test('sales itemized quote creates customer and calculated quote atomically',async()=>{const r=await run();assert.equal(r.status,201);assert.equal(r.data.quotation.amount,33000);const insert=r.calls.find(c=>c.sql.startsWith('insert into public.crm_quotations'));assert.equal(insert.params[0],'customer-id');assert.equal(JSON.parse(insert.params[11])[0].lineTotal,30000);assert.equal(insert.params[14],30);assert.equal(r.calls.at(-1).sql,'COMMIT')});
test('discount sent by Sales blocked before customer creation',async()=>{const r=await run({payload:{...body,discountPercent:10}});assert.equal(r.status,409);assert.equal(r.calls.some(c=>c.sql.startsWith('insert')),false)});
test('below-floor draft can request approval',async()=>{const r=await run({floor:40000,payload:{...body,status:'draft'}});assert.equal(r.status,201);assert.equal(r.data.quotation.requires_approval,true)});
test('quote creation failure rolls back new customer',async()=>{const r=await run({fail:'insert into public.crm_quotations'});assert.equal(r.status,500);assert.equal(r.calls.at(-1).sql,'ROLLBACK')});
test('other roles cannot create quotations',async()=>{const r=await run({role:'accountant'});assert.equal(r.status,403);assert.equal(r.calls.length,0)});
test('private link stores only a hash with expiration',async()=>{const r=await run({path:'/1/share',payload:{}});assert.equal(r.status,200);const token=r.data.path.split('#')[1];assert.equal(token.length,43);const update=r.calls.find(c=>c.sql.startsWith('update public.crm_quotations'));assert.equal(update.params[1],quotationTokenHash(token));assert.match(update.sql,/30 days/)});
test('sales cannot share another salesman quote',async()=>{const r=await run({path:'/1/share',payload:{},creator:'someone-else'});assert.equal(r.status,403);assert.equal(r.calls.some(c=>c.sql.startsWith('update')),false)});
test('draft quotation cannot be shared',async()=>{const r=await run({path:'/1/share',payload:{},quoteStatus:'draft'});assert.equal(r.status,409);assert.equal(r.calls.some(c=>c.sql.startsWith('update')),false)});
