import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';
import {quoteLinkRoutes} from '../src/quote-link-routes.js';import {quotationTokenHash} from '../src/quotation-routes.js';
const token='a'.repeat(43);
async function run({method='GET',path='/',authorization='Bearer '+token,body={amount:30,reference:'UPI-123',acceptQuotation:true},quote=true,amount=100,paid=0,currency='INR',fail='',enabled=true,linked=true}={}){
 const old=process.env.PAYMENT_REVIEW_ENABLED;process.env.PAYMENT_REVIEW_ENABLED=String(enabled);const calls=[],released=[];
 const client={query:async(sql,params)=>{calls.push({sql,params});if(fail&&sql.includes(fail))throw Error('failure');if(sql.includes('from public.crm_quotations'))return {rowCount:quote?1:0,rows:quote?[{id:1,client_id:'client-id',title:'Website',amount,currency,status:'sent',payment_invoice_id:linked?2:null,advance_percent:30,items:[{name:'Website',quantity:1,unitPrice:100,lineTotal:100}]}]:[]};if(sql.includes("from public.crm_invoices where quotation_id")&&!linked)return {rowCount:0,rows:[]};if(sql.startsWith('insert into public.crm_invoices'))return {rowCount:1,rows:[{id:2}]};if(sql.includes('from public.crm_invoices'))return {rowCount:1,rows:[{id:2,amount,paid_amount:paid,status:'issued'}]};if(sql.includes('crm_business_policy'))return {rowCount:1,rows:[{upi_id:'test@upi'}]};if(sql.startsWith('insert into public.crm_payment_submissions'))return {rowCount:1,rows:[{id:3,status:'pending',amount:body.amount}]};return {rowCount:0,rows:[]}},release:x=>released.push(x)};
 const app=express();app.use(express.json());app.use(quoteLinkRoutes({pool:{query:client.query,connect:async()=>client}}));app.use((err,req,res,next)=>res.status(500).json({error:err.message}));const server=app.listen(0,'127.0.0.1');try{await new Promise(r=>server.once('listening',r));const response=await fetch('http://127.0.0.1:'+server.address().port+path,{method,headers:{'Content-Type':'application/json',Authorization:authorization},...(method==='POST'?{body:JSON.stringify(body)}:{})});return {status:response.status,data:await response.json(),calls,released}}finally{await new Promise(r=>server.close(r));if(old===undefined)delete process.env.PAYMENT_REVIEW_ENABLED;else process.env.PAYMENT_REVIEW_ENABLED=old}
}
test('bad link token never touches database',async()=>{const r=await run({authorization:'Bearer 123'});assert.equal(r.status,404);assert.equal(r.calls.length,0)});
test('expired revoked rejected and unapproved quotes are filtered server-side',async()=>{const r=await run({quote:false});assert.equal(r.status,404);assert.match(r.calls[0].sql,/share_expires_at>now\(\)/);assert.match(r.calls[0].sql,/approved_by is not null/);assert.equal(r.calls[0].params[0],quotationTokenHash(token))});
test('link response contains only its quote and its invoice payment history',async()=>{const r=await run({paid:30});assert.equal(r.status,200);assert.equal(r.data.remainingAmount,70);assert.equal(r.data.paidAmount,30);assert.equal('payment_invoice_id' in r.data.quotation,false);assert.equal(r.calls.find(c=>c.sql.includes('crm_payment_submissions')).params[0],2)});
test('part and full payment submissions use the server quote invoice',async()=>{for(const amount of [30,100]){const r=await run({method:'POST',path:'/payments',body:{amount,reference:'UPI123',acceptQuotation:true}});assert.equal(r.status,201);const insert=r.calls.find(c=>c.sql.startsWith('insert into public.crm_payment_submissions'));assert.deepEqual(insert.params,[2,amount,'UPI123']);assert.equal(r.calls.at(-1).sql,'COMMIT');assert.ok(r.calls.some(c=>c.sql.includes("'client_link','submitted'")))}});
test('overpayment does not write a submission',async()=>{const r=await run({method:'POST',path:'/payments',paid:80});assert.equal(r.status,400);assert.equal(r.calls.some(c=>c.sql.startsWith('insert')),false)});
test('payment requires explicit quotation acceptance and cannot override invoice',async()=>{for(const body of [{amount:30,reference:'UPI123',acceptQuotation:false},{amount:30,reference:'UPI123',acceptQuotation:true,invoiceId:999}]){const r=await run({method:'POST',path:'/payments',body});assert.equal(r.status,400);assert.equal(r.calls.length,0)}});
test('non INR quotation cannot use UPI submission',async()=>{const r=await run({method:'POST',path:'/payments',currency:'USD'});assert.equal(r.status,409);assert.equal(r.calls.some(c=>c.sql.startsWith('insert')),false)});
test('audit failure rolls back shared-link submission',async()=>{const r=await run({method:'POST',path:'/payments',fail:'insert into public.crm_payment_audit'});assert.equal(r.status,500);assert.equal(r.calls.at(-1).sql,'ROLLBACK')});
test('disabled payment workflow blocks link payment',async()=>{const r=await run({method:'POST',path:'/payments',enabled:false});assert.equal(r.status,503);assert.equal(r.calls.length,0)});

test('first link payment atomically creates invoice and accepts quotation',async()=>{const r=await run({method:'POST',path:'/payments',linked:false});assert.equal(r.status,201);const created=r.calls.find(c=>c.sql.startsWith('insert into public.crm_invoices'));assert.deepEqual(created.params,['client-id',1,100,'INR']);assert.deepEqual(r.calls.find(c=>c.sql.startsWith('update public.crm_quotations')).params,[1,2]);assert.equal(r.calls.at(-1).sql,'COMMIT')});
test('customer cannot bypass minimum advance through direct API',async()=>{const r=await run({method:'POST',path:'/payments',body:{amount:1,reference:'LOW-123',acceptQuotation:true}});assert.equal(r.status,400);assert.equal(r.calls.some(c=>c.sql.startsWith('insert into public.crm_payment_submissions')),false)});
